'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClientProvider, QueryClient } from '@tanstack/react-query';
import { WebContainer } from '@webcontainer/api';
import { WebContainerProvider } from "@/components/app/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


const webContainerInstance = WebContainer.boot();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = new QueryClient();

  return (
    <html lang="en">
      <body
        className={`dark ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WebContainerProvider instance={webContainerInstance}>
          <QueryClientProvider client={client}>
            {children}
          </QueryClientProvider>
        </WebContainerProvider>
      </body>
    </html>
  );
}
